name: Publish Resume in JSONResume Format as GitHub Page

on:
  push:
    branches: [ main ]

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Log Commit Message
        run: echo "${{ github.event.head_commit.message }}"
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Export Resume as HTML
        uses: kelvintaywl/action-jsonresume-export@v1
        with:
          theme: macchiato
          resume_filepath: resume.json
          output_filepath: docs/index.html

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
        shell: bash

      - name: Commit Changes
        id: commit
        run: |
          if [ -n "$(git status --porcelain docs/index.html)" ]; then
            git add docs/index.html
            git commit -m "[ci skip] chore(docs/index.html): update resume page"
            echo "exit_code=0" >> $GITHUB_ENV
          else
            echo "exit_code=1" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Push Changes
        uses: github-actions-x/commit@v2.9
        if: env.exit_code == '0'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          push: true
